aaryan2134/Engineering-Resources

README.md
I have added 3 more links to the CS resources section and 2 more links to the Competitive Programming section. Please let me know if I need to make any changes. 
This PR is a part of Hacktoberfest 2022.
=> Added 5 more resources to CS resources and CP sections

README.md
Computer Science Resources has been updated now . Kindly Check the changes .
=> Added CS Resources

README.md
Please add the tag of hacktoberfest.
issue no[#17 ]
I have a question can I add paid courses of udemy , I will not add link just name the course
=> added resources for web-dev , ml ,competitive programming

README.md
Includes playlists in Hindi and English.
Includes Notes, Cheatsheet, and Articles
=> Added 5 DBMS Resources

README.md
I have added a new section for java resources and added 5 new resource links. Please let me know if I need to make any changes.
This PR is a part of Hacktoberfest 2022.
=> Added Java Resources

README.md
Added more comprehensive sections in WEB DEVELOPMENT for API, DJANGO, NEXT JS with video as well as documentaries
=> adding additional resources

README.md
added website to visualize any code written in *cpp/c/python/java/javascript*
=> added code visualizer and Git CLI cheatsheet

README.md
Added 5 resources for Operating System including playlist in both English and Hindi,sheets, notes and last-minute revision notes.
=> Added the resource  for Operating System

README.md
I have added the resources for the following subjects -
1. Compiler Design
2. Computer Organization and Architecture
3. MATLAB Programming
4. Software Engineering
5. Theory of Computation
Kindly merge the PR against issue #36.
=> Added the resources for College subjects

README.md
added additional resources for other department wise comprehensive study materials to help engineering students from all backgrounds.
=> added additional ddepts

README.md
=> Added resources for CS

README.md
Here are some resources . have resolved conflicts. If not eligible for hacktoberfest doesn't matter.
=> resources for flutter

Projects/PROJECTS.md, Projects/TODO List/README.md, Projects/TODO List/todo.html, Projects/TODO List/todo.js
I have added the TODO List project , kindly review the issue #35 and merge this PR. Thank you
=> Added TODO List project

README.md
=> Added Kotlin and R

README.md
=> Added App Development resources

README.md
=> Added python resources

README.md
=> Added a resource for Competitive Programming

README.md
=> Added NextJS and AngularJS

README.md
Hello, added 5 resources in mechanical engineering. Submitting as part of hacktoberfest.
=> Added 5 resources to mechanical engineering.

README.md
=> Added computer network resources.

README.md
thank you for reviewing my PR!
=> Added Grid Garden to the CSS Resource List

README.md
Added 6 crucial resources in EE, ME, ML and CP fields
=> Added 6 resources in various fields

README.md
Participating in hacktoberfest, and added some resources in the cyber section.
=> added 5 resources in the cybersecurity section

README.md
- Submitting as part of hacktoberfest.
=> Jetpack compose engineering resources

README.md
Both 6 and 7th youtube links were same
=> Removed dupllicate link

README.md
I added the MUI resources to the README file/ list of resources ! 
Please have a check and merge. This is a hacktoberfest addition as well. 
#109 > done
=> Fix #109 > MUI resources added !

README.md
Starting a resources section for Vue.js. Adding 5 resources for Hacktoberfest 2022 contribution
=> Hacktoberfest 2022 - Adding Vue resources

README.md
=> added more topics in the links to college subjects and then add it in the contents as well #129 

README.md
=> Flutter Resources 
